---
title: "Vis_2"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)

#library(rnoaa)
#remotes::install_github("ropensci/rnoaa", force = TRUE)
```

Import weather data

```{r, message = FALSE, warning = FALSE}
weather_df = read_csv("weather_df.csv")
weather_df = 
  mutate( weather_df,
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"), # creat new name variables.
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

Make a scatterplot but fancy this time.

```{r, message = FALSE, warning = FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  )

```

Scales -- start with `x` and `y` and `colour`

```{r, message = FALSE, warning = FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 20),
    labels = c("-15", "0", "20")
  ) +
  scale_y_continuous(
    limits = c(0, 10),
    transform = "sqrt"
  )
```

Look at color

```{r, message = FALSE, warning = FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  #scale_color_hue(h = c(100, 400)) +
  viridis::scale_color_viridis(discrete = TRUE)
 
```

## Themes

```{r, message = FALSE, warning = FALSE}
ggp_scatterplot = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location", 
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  #scale_color_hue(h = c(100, 400)) +
  viridis::scale_color_viridis(discrete = TRUE)
 
```

```{r, message = FALSE, warning = FALSE}
ggp_scatterplot +
  theme(legend.position = "bottom")#lable place in bottom

```

```{r, warning=FALSE}
ggp_scatterplot +
  theme_bw() + # background is white vs grey upside.
  theme(legend.position = "bottom")
```

Other matters

```{r, warning=FALSE}
ggp_scatterplot +
  theme(legend.position = "bottom") + 
  theme_bw()
  
```

```{r, warning=FALSE}
ggp_scatterplot +
  theme(legend.position = "bottom") + 
  theme_minimal()#background without the lines
```

```{r, warning=FALSE}
ggp_scatterplot +
  theme(legend.position = "bottom") + 
  theme_classic() #background dif
```

```{r, warning=FALSE}
ggp_scatterplot +
  theme(legend.position = "bottom") + 
  ggthemes::theme_excel() #ugly
```

New scatterplot

```{r, warning=FALSE}
weather_df |> 
  ggplot(aes(x = date, y = tmax, colour = name, size = prcp)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +#no grey shadow
  viridis::scale_color_viridis(discrete = TRUE) +
  labs(
    x = "Date",
    y = "Maximum Temp (C)",
    title = "Seasonal variation in Max Temp",
    size = "Precipitation"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

Extra bonus stuff in `ggplot`

Use different datasets in different `geom`s

```{r, warning=FALSE}
central_park_df = 
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df =
  weather_df |> 
  filter(name == "Molokai_HI")
  
molokai_df |> 
  ggplot(aes(x = date, y = tmax, colour = name)) +
  geom_point() +
  geom_line(data = central_park_df)
  
```

## Multiple panels

```{r, warning=FALSE}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density() +
  facet_grid(. ~ name)
```

```{r, warning=FALSE}
ggp_tmax_tmin = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)
ggp_tmax_tmin
  
ggp_tmax_density = 
  weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3) 
ggp_tmax_density

ggp_tmax_date = 
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE)
ggp_tmax_date

#library(patchwork)
(ggp_tmax_tmin + ggp_tmax_density) / ggp_tmax_date# combine 2 plots 
```

## Data manipulation

```{r, warning=FALSE}
weather_df |> 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhile_WA"))) |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = .5)
```

PULSE data next.

```{r}
#install.packages("haven")
library(haven)
pulse_df = read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(visit = ifelse(visit == "bl", "00m", visit))

pulse_df |> 
  ggplot(aes(x = visit, y = bdi_score)) +
  geom_boxplot()

```

Make an FAS plot.

```{r}
litter_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |>  
  separate(group, into = c("dose", "tx_day"), 3)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day",
    names_prefix = "pd_"
  )

fas_df = 
  left_join(pups_df, litter_df, by = "litter_number")

fas_df |> 
  drop_na(tx_day) |> 
  ggplot(aes(x = dose, y = pn_day)) +
  geom_boxplot() +
  facet_grid(tx_day ~ outcome)
  
```












